### ISSUE TITLE
v1.5.1 reports an error after opening: Invalid Dataview query:

### ISSUE THREAD

**Issue by KuiyueRO** [joshuatazrein/obsidian-time-ruler#69]
TimeRuler: v1.5.1
Dataview: v0.5.61
Obsidian: v1.4.16

---

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/63145205/23ae27e4-2e6e-48d3-a9c3-91d8227ad5da)

---

`console.log(this.settings.search);` get: 

```
Uncaught Error: Failed to parse query in 'pagePaths': Error: 
-- PARSING FAILED --------------------------------------------------

> 1 | "仓库/FastStart-Plugins-LongDelay.md" and ()
    |                                          ^

Expected one of the following: 

'!', '(', '-', 'csv(', 'outgoing(', file link, string, tag ('#hello/stuff')

    at DataviewApi.pagePaths (plugin:dataview:18905:19)
    at DataviewApi.pages (plugin:dataview:18927:21)
    at ObsidianAPI.loadTasks (plugin:time-ruler:68430:28)
    at eval (plugin:time-ruler:68642:16)
    at e.tryTrigger (app.js:1:695499)
    at e.trigger (app.js:1:695432)
    at t.trigger (app.js:1:1800309)
    at FullIndex.trigger (plugin:dataview:12687:28)
    at FullIndex.finish (plugin:dataview:12815:14)
    at eval (plugin:dataview:12797:18)
    at async FullIndex.reload (plugin:dataview:12770:13)
pagePaths @ plugin:dataview:18905
pages @ plugin:dataview:18927
loadTasks @ plugin:time-ruler:68430
eval @ plugin:time-ruler:68642
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
trigger @ plugin:dataview:12687
finish @ plugin:dataview:12815
eval @ plugin:dataview:12797
setTimeout（异步）
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
trigger @ plugin:dataview:12687
finish @ plugin:dataview:12815
eval @ plugin:dataview:12797
````

**Comment by renekalff** [comment]
Got the same issue. Temporary fix is to set the Custom Filter to "/".

**Comment by joshuatazrein** [comment]
Got it, seems like a small error breaking. I’ll fix today
